### ISSUE TITLE
meta tag error

### ISSUE THREAD

**Issue by WindProphet** [gibatronic/ngx-superbindex#1]
In your release https://github.com/gibatronic/ngx-superbindex/releases/download/v1.1.0/superbindex.xslt
line 13,14
```
<meta name="version" conent="1.1.0" />
<meta name="viewport" conent="initial-scale=1, minimum-scale=1, shrink-to-fit=no, width=device-width" />
```
The word `content` is written by `conent`, it cause bad performance in mobile version
thank you

**Comment by gibatronic** [comment]
good catch! thanks @WindProphet!
