### ISSUE TITLE
Add "download as zip" button

### ISSUE THREAD

**Issue by Bluscream** [gibatronic/ngx-superbindex#7]
Like on mega.nz, gdrive, dropbox, etc

**Comment by gibatronic** [comment]
Hallo @Bluscream!

I'm afraid this would go beyond the project's basic purpose, since it would require a server to run commands.

I found that [mod_zip](https://www.nginx.com/resources/wiki/modules/zip/) could be helpful, but it looks like a server would still be needed for checksums and whatnot.

**Comment by Bluscream** [comment]
Too bad, maybe someone will make a patch/plugin
