### ISSUE TITLE
No move up link 

### ISSUE THREAD

**Issue by hapylestat** [gibatronic/ngx-superbindex#71]
The xml outputs the content in a way: 

```
<list>
<directory mtime="2021-04-21T01:56:38Z">teamcity</directory>
<file mtime="2021-04-02T09:06:35Z" size="2">test.txt</file>
</list>
```
i.e. without link to parent folder. 

In some way it need to be added...

**Comment by gibatronic** [comment]
Hi there!

Indeed the [ngx_http_autoindex_module](http://nginx.org/en/docs/http/ngx_http_autoindex_module.html) is quite limited, the XML you saw is all that it provides.
But even then, every major browser already offers "go back / forward" functionality, so it would be redundant.

**Comment by Heinrich-F** [comment]
Adding something like:

```xslt
                <a>
                        <xsl:attribute name="class">
                                <xsl:text>parent-link</xsl:text>
                        </xsl:attribute>

                        <xsl:attribute name="href">
                                <xsl:text>..</xsl:text>
                        </xsl:attribute>

                        <xsl:text>..</xsl:text>
                </a>
```

Seems to work just fine for me when added to the xslt before the ordered list. Though I have just discovered this project, and only played around with it a little. If there are subtle bugs I might not have discovered them yet. But I can move up one directory without any immediate problems with this.

So for just linking up one level this works. But if your intention is to get the name of the folder, I guess we are out of luck.

**Comment by BobbyWibowo** [comment]
> If there are subtle bugs I might not have discovered them yet. But I can move up one directory without any immediate problems with this.

The only quirk that I can tell would be that if autoindex is enabled on a root directory, we cannot determine if visitor is currently at said root directory, to then hide the `..` link
